alias: Switch to HDMI 2
description: ""
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: f17_keypress
conditions: []
actions:
  - action: media_player.select_source
    target:
      entity_id: media_player.lg_webos_tv_oled42c31la
    data:
      source: >-
        {% set sources = state_attr('media_player.lg_webos_tv_oled42c31la',
        'source_list') %} {% for s in sources %}
          {% if 'hdmi 2' in s | lower or 'pc' in s | lower %}
            {{ s }}
            {% break %}
          {% endif %}
        {% endfor %}
mode: single
